/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_content_delivery_bucket": "lgorithmisualizer-20230726134934-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://d2k7uu48y6fk6b.cloudfront.net"
};


export default awsmobile;
